services:
  nodejs:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile.local
    volumes:
      - ./nodejs/app/:/usr/src/app
    ports:
      - "3000:3000"
    environment:
     - NODE_ENV=development