services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nodejs:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile.local
    volumes:
      - ./nodejs/app/:/usr/src/app
    ports:
      - "3000:3000"
    environment:
     - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy